<?php $charset='ISO-8859-1';?>
<!-- <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"   "http://www.w3.org/TR/html4/strict.dtd"> -->
<!doctype html>
<html lang="es">
<head>
<meta http-equiv="content-type"
	content="text/html; charset=<?php echo $charset; ?>">
<!--   <meta charset="ISO-8859-1"> -->
<!-- <meta charset="UTF-8"> -->
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>Juegos para contar</title>

<!-- MDB icon -->
<link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">

<!-- Font Quicksand -->
<link
	href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,600,700&display=swap"
	rel="stylesheet">
<!-- Font Patrick Hand para números -->
<link href="https://fonts.googleapis.com/css2?family=Patrick+Hand+SC&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<!-- Your custom styles (optional) -->
<link rel="stylesheet" media="all" href="../css/berta.css">
<link rel="stylesheet" media="all" href="../css/counter.css">

<!-- jQuery -->
<script type="text/javascript" src="../js/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="../js/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="../js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="../js/mdb.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="../js/counter.js"></script>

</head>

<!-- ************ BODY INICIO *************-->
<body>


	<!-- *************- MAIN ************* -->
	<main style='background-color: #ffeeca'>

